CREATE TABLE `staging_jobs` (
 `CONTENTS` blob NOT NULL,
 `NAME` varchar(200) NOT NULL,
 `TYPE` varchar(50) NOT NULL,
 `PUBLICATION_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
 `SHORT_NAME` varchar(200) NOT NULL,
 `MODEL_TYPE` varchar(50) NOT NULL,
 `ID` int(11) DEFAULT NULL,
 `LOCATION_NAME` varchar(200) DEFAULT NULL,
 `CATEGORY_NAME` varchar(100) NOT NULL,
 `LEVEL_NAME` varchar(50) NOT NULL,
 `LEVEL_SHORT_NAME` varchar(10) NOT NULL,
 `REFS_LANDING_PAGE` varchar(100) NOT NULL,
 `COMPANY_ID` int(11) NOT NULL,
 `COMPANY_SHORT_NAME` varchar(500) NOT NULL,
 `COMPANY_NAME` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1